<?php
/**
 * Created by internetsite.com.ua
 * User: Tymofeiev Maksym
 * Date: 27.08.2017
 * Time: 16:51
 */

namespace wokster\tags;


use kartik\select2\Select2;
use wokster\tags\models\Tags;
use yii\helpers\ArrayHelper;

class TagsInputWidget extends Select2
{
  public function init()
  {
    $this->data = ArrayHelper::map(Tags::find()->all(),'name','name');
    $this->options = array_merge($this->options,['multiple'=>true]);
    $this->pluginOptions = array_merge($this->pluginOptions,['tags'=>true]);
    parent::init(); // TODO: Change the autogenerated stub
  }
  public function run()
  {
    parent::run(); // TODO: Change the autogenerated stub
  }
}